name: Update README.md

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 12:00 PM VNT (5:00 AM UTC)
    - cron: '0 09 * * *' # Runs at 8:00 PM VNT (1:00 PM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run GitHub Stats Action
      uses: howznguyen/github-stats@develop
      env:
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        COMMIT_MESSAGE: "🚀 update metrics"
        COMMIT_USER_NAME: "howznguyen"
        COMMIT_USER_EMAIL: "duyntp2000@gmail.com"
        WAKATIME_RANGE: "last_30_days"
        WAKATIME_DATA: "EDITORS,LANGUAGES,OPERATING_SYSTEMS"
        SHOW_METRICS: "COMMIT_TIMES_OF_DAY,LANGUAGE_PER_REPO,COMMIT_DAYS_OF_WEEK"
        TIME_ZONE: "Asia/Ho_Chi_Minh"
        TIME_LAYOUT: "2006-01-02 15:04:05 MST"
        SHOW_LAST_UPDATE: "true"
        ONLY_MAIN_BRANCH: "true"
        HIDE_REPO_INFO: "true"
        EXCLUDE_FORK_REPOS: "true"
        PROGRESS_BAR_VERSION: "1"
